### ISSUE TITLE
prototype pollution warning in object-path@0.11.5

### ISSUE THREAD

**Issue by rachitm99** [mariocasciaro/object-path#101]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/65394139/96617382-2fb26100-1321-11eb-8a1e-c2b02ff079a8.png">

**Comment by mariocasciaro** [comment]
It means that react-scripts has to update its dependency to `object-path`.

**Comment by rachitm99** [comment]
how should i do it ? what are the steps ?

**Comment by mariocasciaro** [comment]
There is no action required from you at the moment. Just run `npm update` regularly to get the latest version of your dependencies once they get updated to resolve the problem. It's the responsibility of the maintainers of your dependencies to fix the problem.

**Comment by rachitm99** [comment]
Thanks 😊
