### ISSUE TITLE
Dependency Check [CWE-471: Modification of Assumed-Immutable Data (MAID)] object-path:0.11.5

### ISSUE THREAD

**Issue by kevinswarner** [mariocasciaro/object-path#108]
We are using OWASP Dependency Check on our project and are seeing this HIGH finding.

```
HIGH (1):
    [CWE-471: Modification of Assumed-Immutable Data (MAID)] object-path:0.11.5
```

We are not using object-path directly, but are using apollo-server, which is using it.

```
apollo-server@2.19.2
  └─┬ apollo-server-core@2.19.2
    └─┬ graphql-upload@8.1.0
      └── object-path@0.11.5
```

I have not seen this issue reported yet.

**Comment by mariocasciaro** [comment]
Hi Kevin, there are no security advisories for version 0.11.5 that I know
of. There is one for versions <= 0.11.4 though, I'm wondering if they are
referring to that.
I would contact the OWASP tool and try to get more information.
