### ISSUE TITLE
Improvement escaped dots

### ISSUE THREAD

**Issue by pocesar** [mariocasciaro/object-path#34]
According to the most arrogant ****head I've ever encountered in Github so far, stating "Please do more research and have something to back up your words before you waste someone's time like this." when I said that object-path already had what he is "reinventing" (littering npm with an useless module called set-value).

object-path is missing a way to handle keys with escaped dots in it. it already does when you use the array notation (eg: `['some.dot.key', 'another.path']`) and only a retarded person (IMHO) would write it as `objectPath.get(obj, 'some\.****head\.is\.stupid');`

sorry for the rant along, but it's amazing how people can be stupid now a days

**Comment by mariocasciaro** [comment]
As you said, object-path already has a way to set dotted properies. Escaping is not going to simplify things but rather complicate them. (Sorry for the late response, I'm on holidays)
