### ISSUE TITLE
support escaping dots in paths

### ISSUE THREAD

**Issue by stevemao** [mariocasciaro/object-path#42]
```js
objectPath.get({'a.b': {b: {c: 'd'}}}, 'a\\.b.b.c').should.eql('d');
```

**Comment by pocesar** [comment]
was already discussed, it's unecessary overhead since you can use the array notation

```js
objectPath.get({'a.b': {b: {c: 'd'}}}, ['a.b','b','c']).should.eql('d');
```

**Comment by stevemao** [comment]
oh, sorry

**Comment by pocesar** [comment]
I'm going to keep this open for now so I remember to add the tests for dot notation in arrays :)

**Comment by stevemao** [comment]
I agree it's an unnecessary overhead since I didn't think about unicode.

**Comment by pocesar** [comment]
done, #44
