### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by pocesar** [mariocasciaro/object-path#61]
Since object-path 1.0+ will revolve around plugins instead of PRs, what about object-path becomes an organization, and all plugins can go inside that? See https://github.com/mariocasciaro/object-path/issues/36#issuecomment-166530144

https://github.com/object-path is available ;)

it can have it's own repo for it's page, better docs, can add collaborators to the team, have a finer grain for issues, etc

**Comment by mariocasciaro** [comment]
Hi Paulo, it's a great idea, it's something I was thinking of doing as well, so let's go ahead with creating the organization. I'll transfer the project as soon as it's ready.
