### ISSUE TITLE
`del` method behaves differently on arrays than `delete` operator

### ISSUE THREAD

**Issue by Lange** [mariocasciaro/object-path#69]
The `delete` operator does not splice from or otherwise modify the length of arrays. It removes that key, but the other elements retain their index.

object-path's `del` method instead uses `splice` ([index.js#L124](https://github.com/mariocasciaro/object-path/blob/master/index.js#L124)), which modifies the length of the array and changes the index of all elements after the deleted element.

For my use case, I would like to use the normal `delete` operator behavior. This would be a breaking change though, so I'm unsure what the best way of approaching this change would be.

Source: [MDN Article on the `delete` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete)

**Comment by pocesar** [comment]
yes, having `undefined` in a sparse array, rather than an array full of items is not expected. it's because most people rarely delete items from an array using the delete operator, because it can break loops in unexpected ways. 

```js
var myArray = new Array(1000);
delete myArray[myArray.push({some: { obj: 'property' }})-1]; // silly isn't it? you have 1001 undefined items in a originally created 1000 indexes array
```

**Comment by Lange** [comment]
Understood. I have a workaround in my code, feel free to close this issue if it's not something you're interested in changing.

**Comment by pocesar** [comment]
what you could do, for example, is return the 'parent' array, then delete it yourself, like:

```js
var deep = objectPath.get(someObj, 'some.deep.array', []); // some.deep.array.10 would be some.deep.array[10]
delete deep[10];
```

**Comment by Lange** [comment]
Thanks! That's currently what I'm doing in my code.

**Comment by doc987** [comment]
What about having two different functions (or one function with an option) so that the user can choose to delete with or without re-indexing the array?
