### ISSUE TITLE
get a null path not return the defaultValue

### ISSUE THREAD

**Issue by yesmeck** [mariocasciaro/object-path#77]
See https://runkit.com/586945e631af31001472d7f4/5871ebc5fe814b0013db83e5

**Current behavior:** 

return the whole object.

**Expected behavior:**

return the defaultValue.

Related code: https://github.com/mariocasciaro/object-path/blob/2b80d6cf4e0939e59e525cc1f65da18ad8767beb/index.js#L224-L229

**Comment by mariocasciaro** [comment]
Null path is equivalent to an empty path, so the entire object is returned. This is the expected result.

**Comment by yesmeck** [comment]
So are these https://github.com/mariocasciaro/object-path/blob/2b80d6cf4e0939e59e525cc1f65da18ad8767beb/index.js#L227-L229 dead code?

**Comment by mariocasciaro** [comment]
That line checks the object not the path.

**Comment by yesmeck** [comment]
Sorry, miss it.
