### ISSUE TITLE
Question/Enhancement: Return nested values from array

### ISSUE THREAD

**Issue by ZephD** [mariocasciaro/object-path#82]
Suppose I have a object like this:

`const obj = {
  tags: [
    {name: 'one'},
    {name: 'two'},
    {name: 'three'},
  ]
}`

I read from the API that you can get a single value of a known index:
`ObjectPath.get(obj,'tags.1.name') // returns 'two'`

But does object-path allow for a path that can map the nested 'name' value?

e.g.
`ObjectPath.get(obj,'tags.*.name') // returns ['one','two','three']`

Thanks

**Comment by ianhenderson** [comment]
Seems like this could be done pretty well with plain js though:
```js
ObjectPath.get(obj, 'tags', []).map(t => t.name)
```

**Comment by jasonphillips** [comment]
If you're looking for it to be a `.get`-like method with a similar structure, deeper props on the right hand side of the asterisk, and no manual map() needed each time, you could just add something like this to your local ObjectPath:

 ```js
objectPath.getAll = (object, path, flatten) => {
    const agg = flatten ? (arr) => arr : (arr) => [arr];
    
    if (typeof(path)=='string' && path.indexOf('.*.')>0) {
      return objectPath.get(object, path.split('.*.')[0], []).reduce(
        (results, item) => results.concat(
            agg(objectPath.getAll(item, path.split('.*.')[1]), flatten)
        ), []
      );
    }
    if (typeof(path)=='object' && path.indexOf('*')>0) {
      return objectPath.get(object, path.slice(0, path.indexOf('*')), []).reduce(
        (results, item) => results.concat(
            agg(objectPath.getAll(item, path.slice(path.indexOf('*') + 1)), flatten)
        ), []
      )
    }
    return objectPath.get(object, path);
}
```

Usage:

```js

const obj = { 
  tags: [ 
    {
        name: 'one', 
        deeper: {id: 13}, 
        related: [
            {id:10}, {id:5}
        ]
    }, 
    {
        name: 'two', 
        deeper: {id: 29}, 
        related: [
            {id:1}
        ]
    }, 
    {
        name: 'three', 
        deeper: {id: 5},
        related: [
            {id: 2}, {id:23}
        ]
    }, 
    {
        name: 'four', 
        deeper: {id: 32},
        related: [
            {id: 1}
        ]
    }
] }

/* 
  works with strings or arrays 
*/
objectPath.getAll(obj, 'tags.*.name')
// => ["one","two","three","four"]

objectPath.getAll(obj, ['tags','*','name'])
// => ["one","two","three","four"]

/*
  can descend further 
*/
objectPath.getAll(obj, 'tags.*.deeper.id')
// => [13,29,5,32]

/*
  can handle multiple wildcards
*/
objectPath.getAll(obj, ['tags','*','related','*','id'])
// => [[10,5],[1],[2,23],[1]]

/*
  additional option to flatten nested results
*/
objectPath.getAll(obj, ['tags','*','related','*','id'], true)
// => [10,5,1,2,23,1]
```

I do see why you'd want this, especially for cases of looking to quickly pull a list of related items that is itself located within another list.

**Comment by revelt** [comment]
@ZephD are you satisfied with the above solution and if so, can we close this issue?

**Comment by ZephD** [comment]
I ended up using a different library, sorry.

My reason for posting was a question or maybe to spark an idea for an enhancement, rather than an issue.
Perhaps the above solution could be that enhancement? If you'd like.

Thanks!
