### ISSUE TITLE
If a property has null value, throws an error instead of creating path

### ISSUE THREAD

**Issue by pravinkumart** [mariocasciaro/object-path#93]
I have an object like `a = { a: null }`

When i try to execute `objectpath.set(a, 'a.b', '3');`, it throws an error 
`TypeError: Cannot set property 'b' of null`

**Comment by mariocasciaro** [comment]
I'd consider a null property already set. I don't think the library should override values already set.

**Comment by pravinkumart** [comment]
I couldn't understand the explanation.

As you know **'void 0' just checks for undefined and skips other primitive values like null, empty string('')**.This leads to throwing error.
**Example:**
To get following output,
`a = { a: { b: 3 } }`

Consider 3 input cases, Case 1 and Case 2 works fine, but Case 3 fails and throws an error.

**Case 1:**
`var a = { a: undefined };`

**Case 2:**
`var a = {};`

**Case 3:**
`var a = { a: null };`

**To make sure even Case 3 works, i have the changed the code like this.**

Can you please explain your concern once more ?

**Comment by mariocasciaro** [comment]
I think that `null` should be treated as if the value has been already set - to `null` indeed - and it should be left as it is by `object-path`. Considering `null` as an `undefined` is a legit behaviour, but for object path I'd prefer to consider `null` a value, as if it was an integer or a boolean.
