### ISSUE TITLE
how to get a path of a key?

### ISSUE THREAD

**Issue by CavalcanteLeo** [mariocasciaro/object-path#99]
how to get a path of a key?
not the value.

I'm iterating(deep) all object keys, and store some important keys in another object, since my loop is in an important key, i want to store it, but how can i convert to a path?

```javascript
const obj = {
   foo: {
      bar: true
   }
}
```

i want to return `'foo.bar'`

**Comment by PAEz** [comment]
Doesnt sound like something this should do.
If your iterating over the object then why cant you build the path as you go?
